resources:
  # Git repo with Dockerfile + manifests
  - name: concourse-examples
    type: git
    icon: github
    source:
      uri: https://github.com/amitopenwriteup/javadockerproject.git
      branch: main

  # Docker registry (where image will be pushed)
  - name: simple-image
    type: registry-image
    icon: docker
    source:
      repository: ((image-repo-name))/simple-image
      tag: latest
      username: ((registry-username))
      password: ((registry-password))

jobs:
- name: build-scan-push-deploy
  plan:
  # Step 1: Get source code
  - get: concourse-examples
    trigger: true

  # Step 2: Build Docker image
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
        - name: concourse-examples
      outputs:
        - name: image
      params:
        CONTEXT: concourse-examples
      run:
        path: build

  # Step 3: Scan with Trivy
  - task: trivy-scan
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: aquasec/trivy
          tag: latest
      inputs:
        - name: image
      run:
        path: sh
        args:
          - -exc
          - |
            echo "=== Running Trivy scan ==="
            trivy image --exit-code 1 --severity CRITICAL,HIGH --input image/image.tar || {
              echo "Vulnerabilities found! Failing build."
              exit 1
            }

  # Step 4: Push image to registry
  - put: simple-image
    params:
      image: image/image.tar

  # Step 5: Deploy to Kubernetes
  - task: deploy-k8s
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: bitnami/kubectl
          tag: latest
      inputs:
        - name: concourse-examples
      params:
        IMAGE: ((image-repo-name))/simple-image:latest
        KUBECONFIG_CONTENT: ((kubeconfig))   # base64-encoded kubeconfig secret
      run:
        path: sh
        args:
          - -exc
          - |
            echo "=== Deploying to Kubernetes ==="
            mkdir -p /tmp/kubeconfig
            echo "$KUBECONFIG_CONTENT" | base64 -d > /tmp/kubeconfig/config
            export KUBECONFIG=/tmp/kubeconfig/config
            sed "s|REPLACE_IMAGE|$IMAGE|g" concourse-examples/k8s/deployment.yaml > /tmp/deployment.yaml
            kubectl apply -f /tmp/deployment.yaml
            kubectl rollout status deployment/simple-app
